kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:14.21.3
    volumes:
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn
      - yarn build
    environment:
      CI: false

  - name: deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/blog/
      - rm -rf /webroot/blog/*
      - cp -rf ./public/* /webroot/blog/

  - name: deploy-cdn
    image: node:14.21.3
    commands:
      - yarn deploy
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: COS_SECRET_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: COS_SECRET_KEY

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
